Repository Rangi42/polishedcrystal, pull requests merged in 2025-03, with the labels that each got.

#1081 Split tileset graphics into their own sections
  constants/tileset_constants.asm
  data/tilesets.asm
  home/map.asm
  ram/wramx.asm
Labels: refactoring, patch-version

#1078 FAQ/README tweaks
  FAQ.md
  README.md
  data/pokemon/base_stats/bellsprout.asm
  data/pokemon/base_stats/gloom.asm
  data/pokemon/base_stats/oddish.asm
  data/pokemon/base_stats/weepinbell.asm
Labels: documentation

#1099 Don't reload walked tiles if walking onto/leaving `COLL_COAST_SAND`
  engine/overworld/player_step.asm
  home/map.asm
Labels: cosmetic, patch-version

#1137 Magikarp length
  constants/misc_constants.asm
  engine/battle/core.asm
  engine/events/magikarp.asm
  engine/menus/intro_menu.asm
Labels: minor-version

#1135 Bloodmoon Ursaluna event
  CREDITS.md
  constants/battle_constants.asm
  constants/engine_flags.asm
  constants/event_flags.asm
  constants/ram_constants.asm
  constants/trainer_constants.asm
  data/events/engine_flags.asm
  data/pokemon/base_stats/ursaluna_bloodmoon.asm
  data/pokemon/egg_move_pointers.asm
  data/pokemon/evos_attacks.asm
  data/pokemon/invalid_variants.asm
  data/pokemon/overworld_icon_pals.asm
  data/trainers/parties.asm
  engine/battle/core.asm
  engine/battle/move_effects/roar.asm
  engine/battle/move_effects/teleport.asm
  engine/events/specials.asm
  engine/pokemon/move_mon.asm
  gfx/pokemon/ursaluna_bloodmoon/anim.asm
  gfx/pokemon/ursaluna_bloodmoon/anim_idle.asm
  gfx/pokemon/ursaluna_bloodmoon/back.png
  gfx/pokemon/ursaluna_bloodmoon/front.png
  gfx/pokemon/ursaluna_bloodmoon/normal.pal
  gfx/pokemon/ursaluna_bloodmoon/shiny.pal
  maps/FuchsiaGym.asm
  maps/LakeOfRage.asm
  maps/MurkySwamp.ablk
  maps/MurkySwamp.asm
  maps/VioletOutskirtsHouse.asm
Labels: scripting

#1091 Migrate Evos/Attacks to macros
  data/pokemon/evos_attacks.asm
  data/pokemon/evos_attacks_pointers.asm
Labels: refactoring, optimizations, patch-version
