Repository Rangi42/polishedcrystal, pull requests merged in 2025-02, with the labels that each got.

#978 Summary screen
  CREDITS.md
  Makefile
  constants/cgb_constants.asm
  constants/menu_constants.asm
  constants/summary_constants.asm
  data/abilities/descriptions.asm
  data/mon_menu.asm
  data/predef_pointers.asm
  engine/battle/core.asm
  engine/gfx/cgb_layouts.asm
  engine/gfx/color.asm
  engine/gfx/item_icons.asm
  engine/gfx/load_font.asm
  engine/gfx/mon_icons.asm
  engine/link/link.asm
  engine/pc/bills_pc_ui.asm
  engine/pokedex/pokedex.asm
  engine/pokemon/mon_menu.asm
  engine/pokemon/mon_stats.asm
  engine/pokemon/mon_submenu.asm
  engine/pokemon/party_menu.asm
  engine/pokemon/stats_screen.asm
  engine/pokemon/summary/blue_page.asm
  engine/pokemon/summary/egg_page.asm
  engine/pokemon/summary/green_page.asm
  engine/pokemon/summary/orange_page.asm
  engine/pokemon/summary/pink_page.asm
  engine/pokemon/summary_screen.asm
  gfx/font.asm
  gfx/misc.asm
  gfx/stats/pages.pal
  gfx/stats/stats.png
  gfx/stats/status.png
  gfx/stats/summary.png
  gfx/stats/summary_sprites.png
  home/lcd.asm
  home/vblank.asm
  includes.asm
  macros/gfx.asm
  main.asm
  maps/PlayersHouse2F.asm
  ram/wram0.asm
Labels: cosmetic, patch-version

#971 Update evos_attacks.asm
  data/pokemon/evos_attacks.asm
Labels: moves, patch-version, game balance

#1064 new move tutors
  audio/alternate_music.asm
  constants/event_flags.asm
  constants/music_constants.asm
  data/moves/tmhm_moves.asm
  maps/MahoganyMart1F.asm
  maps/Route1617Gate2F.asm
  maps/Route35NationalParkGate.asm
Labels: enhancement, moves, scripting

#1055 add Polished specific in-game tips
  maps/EcruteakCity.ablk
  maps/EcruteakCity.asm
  maps/IlexForest.ablk
  maps/IlexForest.asm
  maps/Route43.asm
Labels: scripting, patch-version
